### ISSUE TITLE
Diretório hardcoded

### ISSUE THREAD

**Issue by raulikeda** [gabrielvf1/InfraAWS#1]
na função criandoKeys(self):

está em hardcoded o seu usuário (gabrielfv).

Traceback (most recent call last):
  File "InfraAWS-GabrielFrancato.py", line 668, in <module>
    RDS.criandoKeys()
  File "InfraAWS-GabrielFrancato.py", line 604, in criandoKeys
    with open("/home/gabrielvf/.ssh/privada_projeto_ohio.pem", 'w+') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gabrielvf/.ssh/privada_projeto_ohio.pem'

**Comment by gabrielvf1** [comment]
Oi Raul acabei nem notando que o usuário estava hardcoded, posso fazer alguma coisa para arrumar? Desculpa ai!
